baseurl = "http://esolia.co.jp/"
title = "イソリア㊑"
contentdir = "content/ja"
publishdir = "public/ja"
canonifyurls = "false"
copyright = "This work is copyright. All rights reserved by eSolia Inc."
MetaDataFormat = "yaml"
# For RSS only, apparently
languageCode = "ja-JP"

[author]
    name = "Rick Cogley"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:section/:slug"

[taxonomies]
    tag = "tags"
    topic = "topics"
    series = "series"

[blackfriday]
    plainIdAnchors = true

[params]
    locale = "ja-JP"
    alternatelocales = ["en-US"]
    description = "東京をベースにしたITマネージメントやサポート会社、株式会社イソリアのウェブサイト"
    keywords = ["日本","IT","マネージメント","サポート","アウトソーシング","ヘルプデスク","ウェブサイト","開発","統括"]
    author = "チーム イソリア"
    accountableperson = "コブレー ジェームズ"
    entityname = "株式会社イソリア"
    # Used when a given page doesn't set its own.
    defaultDescription = "このコンテンツはイソリアの提供でお送りいたします。"
    defaultKeywords = "イソリア"
    ISO8601 = "2006-01-02T15:04:05JST"
    googleAnalytics = "UA-1040233-8"
