baseurl = "http://esolia.com/"
title = "eSolia Inc."
contentdir = "content/en"
publishdir = "public/en"
canonifyurls = "false"
copyright = "This work is copyright. All rights reserved by eSolia Inc."
MetaDataFormat = "yaml"
# For RSS only, apparently
languageCode = "en-us"

[author]
    name = "Rick Cogley"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:section/:slug"

[taxonomies]
    tag = "tags"
    topic = "topics"
    series = "series"

[params]
    locale = "en-us"
    description = "Website of eSolia Inc. - a Tokyo-based IT Management and support firm."
    keywords = "Japan,IT,Management,Support,Outsourcing,Helpdesk,Website,Development,Operations"
    author = "Team eSolia"
    # Used when a given page doesn't set its own.
    defaultDescription = "Content by eSolia Inc."
    defaultKeywords = "eSolia"
    ISO8601 = "2006-01-02T15:04:05JST"
    googleAnalytics = "UA-1040233-7"
